title: SH Articles & Journal # name of the site
author: Syafiq Hadzir # name of site's author
email: syafiqhadzir@live.com.my # email of site's author
url: https://syafiqhadzir.dev # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Always becoming that another guy who codes and writes.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
